In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [4]:
df.drop(['PassengerId','Name','Ticket','Cabin'], axis=1, inplace=True)
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df["Sex"] = le.fit_transform(df["Sex"])
df["Embarked"] = le.fit_transform(df["Embarked"])

In [6]:
df.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

# SVM

In [7]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score

In [8]:
def svm_model(col):
        
    svmmod = svm.SVC(gamma = 0.01, C = 100)

    for i in col:
        x = df.drop([i], axis=1)
        y = df[i]
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.3, random_state=0)
        svmmod.fit(x_train,y_train)
        
        print("Dependent Variable is", i, " and rest are Independent Variables")
        
        y_pred = svmmod.predict(x_test)
    
        print("Accuracy : ", accuracy_score(y_test, y_pred, normalize=True))
        print("Confusion matrix : \n",confusion_matrix(y_test, y_pred))
              
        print("==============================================")


In [9]:
col= ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch','Embarked']        
svm_model(col)

Dependent Variable is Survived  and rest are Independent Variables
Accuracy :  0.7415730337078652
Confusion matrix : 
 [[124  33]
 [ 36  74]]
Dependent Variable is Pclass  and rest are Independent Variables
Accuracy :  0.9026217228464419
Confusion matrix : 
 [[ 64   4   2]
 [  4  36   9]
 [  1   6 141]]
Dependent Variable is Sex  and rest are Independent Variables
Accuracy :  0.7265917602996255
Confusion matrix : 
 [[ 66  32]
 [ 41 128]]
Dependent Variable is SibSp  and rest are Independent Variables
Accuracy :  0.7490636704119851
Confusion matrix : 
 [[150  24   7   0   1   0   0]
 [ 21  39   5   0   0   0   0]
 [  4   1   3   0   0   0   0]
 [  0   2   1   3   1   0   0]
 [  0   0   0   0   2   0   0]
 [  0   0   0   0   0   1   0]
 [  0   0   0   0   0   0   2]]
Dependent Variable is Parch  and rest are Independent Variables
Accuracy :  0.797752808988764
Confusion matrix : 
 [[187   6   5   0   0   0]
 [ 21  15   3   0   0   1]
 [ 10   6  11   0   0   0]
 [  0   0   1   0   0   0]
 