In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.shape

(889, 12)

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [5]:
df1 = df.drop(['PassengerId','Name','Ticket','Cabin'], axis=1)
df1.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df1["Sex"] = le.fit_transform(df1["Sex"])
df1["Embarked"] = le.fit_transform(df1["Embarked"])

In [7]:
df1.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

# Naive Bayes

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import * 
from sklearn.metrics import accuracy_score, confusion_matrix

In [9]:
def nb(col):    
    clf = BernoulliNB()
    for i in col:
        x = df1.drop([i], axis=1)
        y = df1[i]
        llist = df1.columns.to_list()
        llist.remove(i)
        print('Dependent Variable:', i)
        print('Independent Variables:', *llist)
    
        x_train, x_test, y_train, y_test = train_test_split(x, y, test_size =0.3, random_state=0)
        model = clf.fit(x_train,y_train)
        pred = model.predict(x_test)
    
        print(f"\nAcuuracy for {i} is: ", accuracy_score(y_test, pred, normalize=True))
        print(f"Confusion matrix for {i} is \n", confusion_matrix(y_test, pred))
        print("===================================================")

In [10]:
col = ['Survived', 'Pclass', 'Sex', 'SibSp', 'Parch','Embarked']        
nb(col)

Dependent Variable: Survived
Independent Variables: Pclass Sex Age SibSp Parch Fare Embarked

Acuuracy for Survived is:  0.7715355805243446
Confusion matrix for Survived is 
 [[131  26]
 [ 35  75]]
Dependent Variable: Pclass
Independent Variables: Survived Sex Age SibSp Parch Fare Embarked

Acuuracy for Pclass is:  0.5917602996254682
Confusion matrix for Pclass is 
 [[ 30   8  32]
 [  9  10  30]
 [ 24   6 118]]
Dependent Variable: Sex
Independent Variables: Survived Pclass Age SibSp Parch Fare Embarked

Acuuracy for Sex is:  0.7453183520599251
Confusion matrix for Sex is 
 [[ 49  49]
 [ 19 150]]
Dependent Variable: SibSp
Independent Variables: Survived Pclass Sex Age Parch Fare Embarked

Acuuracy for SibSp is:  0.6891385767790262
Confusion matrix for SibSp is 
 [[162  20   0   0   0   0   0]
 [ 43  22   0   0   0   0   0]
 [  6   2   0   0   0   0   0]
 [  5   2   0   0   0   0   0]
 [  2   0   0   0   0   0   0]
 [  1   0   0   0   0   0   0]
 [  2   0   0   0   0   0   0]]
Dependent 