# Assignment

In [1]:
import numpy as np

## Q1. Create a 3x3x3 array with random values.

In [2]:
# Ans1.
x = np.random.random((3,3,3))
print('3x3x3 Array: ')
print(x)
print('Shape:',x.shape)

3x3x3 Array: 
[[[0.55730997 0.45441129 0.33571967]
  [0.90810397 0.9483115  0.47617735]
  [0.09499623 0.12041623 0.11290011]]

 [[0.24541529 0.67024269 0.33612315]
  [0.52813118 0.63734707 0.48102256]
  [0.91231698 0.15938051 0.26148356]]

 [[0.74789865 0.20969568 0.52118422]
  [0.97831166 0.43906462 0.86970117]
  [0.23098918 0.05331374 0.6368639 ]]]
Shape: (3, 3, 3)


## Q2. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.

In [3]:
# Ans2. 
y = np.zeros((5,5))
for i in range(len(y)):
    for j in range(len(y)):
        if(i==j+1):
            y[i][j]=i
print(y)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## Q3. Create a 8x8 matrix and fill it with a checkerboard pattern.

In [4]:
# Ans3. 
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Q4. Normalize a 5x5 random matrix.

In [5]:
# Ans4.
a = np.random.randn(5,5)
print("Before:\n")
print(a)

amax, amin = a.max(), a.min()
a = (a - amin)/(amax - amin)

print("\nAfter:\n")
print(a)

Before:

[[ 0.64305691  0.27379953  1.72046172 -0.27565441 -0.37268213]
 [-0.64862126 -0.78514069 -0.79681565 -0.28238804  0.92546322]
 [-2.05482689  0.10598264 -0.28363704  0.4020496   1.08837366]
 [-1.25375514  1.97319248 -0.79843375 -0.23043551  1.21927198]
 [ 1.10408398  0.826327   -0.8035545   0.16795703 -0.14629187]]

After:

[[0.66977925 0.57810705 0.93725682 0.44169909 0.41761089]
 [0.34910597 0.31521353 0.31231509 0.44002739 0.73988971]
 [0.         0.53644467 0.43971731 0.60994654 0.78033402]
 [0.19887485 1.         0.31191338 0.45292517 0.81283096]
 [0.78423428 0.71527806 0.3106421  0.55183049 0.47381476]]


## Q5. How to find common values between two arrays?

In [6]:
# Ans5.
a1 = np.array([1,5,7,9,8,5])
a2 = [6,9,7,9,5]
print("Array 1: ", a1)
print("Array 2: ", a2)
print("Common values between two arrays:", np.intersect1d(a1, a2))

Array 1:  [1 5 7 9 8 5]
Array 2:  [6, 9, 7, 9, 5]
Common values between two arrays: [5 7 9]


## Q6. How to get the dates of yesterday, today and tomorrow?

In [7]:
#Ans6.
import datetime as dt
today = dt.date.today()
yesterday = today - dt.timedelta(days = 1)
tomorrow = today + dt.timedelta(days = 1) 

print('Yesterday: ',yesterday)
print('Today: ', today)
print('Tomorrow: ', tomorrow)

Yesterday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


## Q7. Consider two random array A and B, check if they are equal.

In [8]:
# Ans7.
a = np.array([5,3,1,4,2])
b =  np.array([1,2,3,4,5])
print('Array 1:\n', a)
print('Array 2:\n', b)
print('True if two arrays are equal')
print('False if two arrays are equal')
np.array_equal(a,b)

Array 1:
 [5 3 1 4 2]
Array 2:
 [1 2 3 4 5]
True if two arrays are equal
False if two arrays are equal


False

## Q8. Create random vector of size 10 and replace the maximum value by 0.

In [9]:
# Ans8.
v = np.random.randn(10,1)
print('Random Vector: ')
print(v)
max_val = np.amax(v)
print('Maximum Value in the vector is: ',max_val)
loc = np.where(v==max_val)
v[loc] = 0
print('Updated vector is: ')
print(v)

Random Vector: 
[[-1.10046884]
 [-0.6064781 ]
 [ 0.44016142]
 [-0.30985938]
 [ 0.76557149]
 [ 2.42458562]
 [-0.92748183]
 [-0.05671949]
 [ 0.70633231]
 [ 0.67650707]]
Maximum Value in the vector is:  2.424585623864498
Updated vector is: 
[[-1.10046884]
 [-0.6064781 ]
 [ 0.44016142]
 [-0.30985938]
 [ 0.76557149]
 [ 0.        ]
 [-0.92748183]
 [-0.05671949]
 [ 0.70633231]
 [ 0.67650707]]


## Q9. How to print all the values of an array?

In [10]:
#Ans9.
d = np.random.randn(3,3)
print("The array is:")
print(d)
for i in range(len(d)):
    for j in range(len(d)):
        print("The value at index(",i,",",j,")is:",d[i][j])

The array is:
[[-0.27936223 -0.20580961  0.17951216]
 [-0.50834851  1.55479785 -0.08633245]
 [ 0.15461186  1.76072376  1.09722922]]
The value at index( 0 , 0 )is: -0.27936223463006776
The value at index( 0 , 1 )is: -0.2058096134932729
The value at index( 0 , 2 )is: 0.17951215562910916
The value at index( 1 , 0 )is: -0.5083485147335729
The value at index( 1 , 1 )is: 1.5547978491712635
The value at index( 1 , 2 )is: -0.08633245020347373
The value at index( 2 , 0 )is: 0.15461186225636062
The value at index( 2 , 1 )is: 1.7607237597269316
The value at index( 2 , 2 )is: 1.097229224368524


## Q10. Subtract the mean of each row of a matrix.

In [11]:
# Ans10.
arr = np.random.randn(3,3)
print("Initially:")
print(arr)
print("The mean value of each row is:")
arr1=np.mean(arr,axis=1)
print(arr1)
arr2=arr-arr1
print("Matrix after mean is subtracted")
print(arr2)

Initially:
[[ 0.72563811  1.44906747  0.89853889]
 [ 0.54811858  0.73224781 -1.39148682]
 [ 0.61060708 -0.33906419 -0.25269769]]
The mean value of each row is:
[ 1.02441483 -0.03704014  0.00628173]
Matrix after mean is subtracted
[[-0.29877671  1.48610762  0.89225716]
 [-0.47629625  0.76928796 -1.39776855]
 [-0.41380775 -0.30202405 -0.25897943]]


## Q11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [12]:
# Ans11.
k = np.random.rand(5)
print("Initial Vector:\n",k)
i = np.random.randint(0, len(k),5)
print("Random Values:\n",i)
k += np.bincount(i, minlength=len(k))
print("Resultant Vector:\n",k)

Initial Vector:
 [0.66803292 0.84834203 0.59745213 0.11140291 0.18741549]
Random Values:
 [3 0 2 3 3]
Resultant Vector:
 [1.66803292 0.84834203 1.59745213 3.11140291 0.18741549]


## Q12. How to get the diagonal of a dot product?

In [13]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
print("Array A:\n", A)
print("\nArray B:\n", B)
print('\nDot product:\n',np.dot(A,B))
dot = np.diag(np.dot(A, B))
print('\nDiagonal Elements are:\n', dot)

Array A:
 [[7 9 7]
 [3 2 0]
 [9 5 8]]

Array B:
 [[3 9 5]
 [9 0 4]
 [8 2 5]]

Dot product:
 [[158  77 106]
 [ 27  27  23]
 [136  97 105]]

Diagonal Elements are:
 [158  27 105]


## Q13. How to find the most frequent value in an array?

In [14]:
# Ans13.
g = np.random.randint(0,10,15)
print(g)
print('Most frequent value: ',np.bincount(g).argmax())

[9 7 3 9 3 0 7 6 2 3 5 7 3 6 8]
Most frequent value:  3


## Q14. How to get the n largest values of an array?

In [16]:
# Ans14.
s = np.arange(100)
np.random.shuffle(s)
n = int(input('Enter the value of n: '))
print (s[np.argpartition(-s,n)[:n]])

Enter the value of n: 5
[99 95 97 98 96]


## Q15. How to create a record array from a regular array?

In [17]:
# Ans15.
x1 = np.array(['T','A','V','I','S','H'])
x2 = np.array([1,2,3,4,5,6])

print('Regular Array 1:',x1)
print('Regular Array 2:',x2)

records = np.core.records.fromarrays([x1,x2], names='Col1, Col2') # The arrays are now transposed 

print('\nRecorded Array:', records)

Regular Array 1: ['T' 'A' 'V' 'I' 'S' 'H']
Regular Array 2: [1 2 3 4 5 6]

Recorded Array: [('T', 1) ('A', 2) ('V', 3) ('I', 4) ('S', 5) ('H', 6)]
